apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vboxvms.amlight.net
spec:
  group: amlight.net
  scope: Namespaced
  names:
    plural: vboxvms
    singular: vboxvm
    kind: VirtualboxVM
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                ip:
                  type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: IP
          type: string
          jsonPath: .spec.ip
