apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vboxvms-cluster-role
rules:
- apiGroups:
  - amlight.net
  resources:
  - vboxvms
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: XXXSERVICEACCOUNTXXX-vboxvms-role-binding
  namespace: XXXNAMESPACEXXX
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vboxvms-cluster-role
subjects:
- kind: ServiceAccount
  name: XXXSERVICEACCOUNTXXX
  namespace: XXXNAMESPACEXXX
